### ISSUE TITLE
High processor usage

### ISSUE THREAD

**Issue by buraga-dmitrii** [pheen/fuzzy_ruby_server#13]
Sometimes it loads all possible processors

<img width="1433" alt="fuzzy_processor_loading" src="https://github.com/pheen/fuzzy_ruby_server/assets/29340720/1d697733-052b-409f-bec1-090cf38f0e14">

**Comment by pheen** [comment]
Yes the indexing should running quite hot. Once it's done indexing it should chilling out, if not I'm not sure.

**Comment by buraga-dmitrii** [comment]
How long does it takes? If it continues more than 5 minutes - is it a problem?
