### ISSUE TITLE
Installation question w/ neovim/coc.nvim

### ISSUE THREAD

**Issue by timtyrrell** [pheen/fuzzy_ruby_server#14]
I apologize for this question but do I need to clone this repo and get the binaries in my bin PATH to use it? Did you publish the binary to a registry?

For an example of how I would configure this, it would be similar to [Sublime Text LSP](https://shopify.github.io/ruby-lsp/EDITORS_md.html#sublime-text-lsp) that `ruby-lsp` has in their docs. The [coc.nvim](https://github.com/neoclide/coc.nvim/wiki/Language-servers#register-custom-language-servers) docs are here but I don't mean for you to have to dig around in them.

Also, I am not super knowledgeable about rust but there is an existing crate named [fuzzy](https://crates.io/crates/fuzzy) that threw me off because I see your package has the same name in your [cargo.toml](https://github.com/pheen/fuzzy_ruby_server/blob/6f1f2170aa6815648cc7dc40c6e2e6d3f658b4dd/Cargo.toml#L2) file

**Comment by delbetu** [comment]
same question here, as neovim user with no knowledge of rust isn't clear to me how to get the `fuzzy` command available to neovim.
would awesome if I could do `cargo install fuzzy_ruby_server`

**Comment by iovis** [comment]
I think what I did was just to clone the repo and `cp bin/fuzzy_<your_architecture> <somewhere_in_your_PATH>/fuzzy`.

If you want to build it yourself, I'm guessing you can just run `cargo build --release` and then `cp target/release/fuzzy <some PATH>/fuzzy`

**Comment by delbetu** [comment]
Thanks @iovis this worked for me:
```bash
curl -o ~/bin/fuzzy -L https://github.com/pheen/fuzzy_ruby_server/raw/master/bin/fuzzy_darwin-arm64
chmod +x ~/bin/fuzzy
```

Although I would like to have an easy way to ask neovim to update all the installed lsp-servers

**Comment by timtyrrell** [comment]
One thought is you could rig up something like the following, I am still using [vim-plug](https://github.com/junegunn/vim-plug) so my example would run anytime the plugins update:

```
Plug 'pheen/fuzzy_ruby_server', { 'do': '~/.config/utils/move_binary_and_chmod.sh' }
```

**Comment by timtyrrell** [comment]
Alright, so shoving this in my `coc-settings.json` seems to do the trick for me after, I did the `curl` method mentioned above. 👍 

```
{
  ...
  "languageserver": {
    "fuzzyRubyServer": {
      "command": "fuzzy",
      "initializationOptions": {
        "allocationType": "ram",
        "indexGems": true,
        "reportDiagnostics": true
      },
      "filetypes": ["ruby"]
    },
  }
  ...
}
```

**Comment by pheen** [comment]
Yup `cargo build --release` is the way if you need to build the binary yourself. Also see https://github.com/pheen/fuzzy_ruby_server#publishing which shows how to build for other platforms. Sorry I'm not planning on working on this project anymore for the foreseeable future.
