### ISSUE TITLE
Support exit notification

### ISSUE THREAD

**Issue by etherbob** [pheen/fuzzy_ruby_server#16]
Per a report from another user who tested out building and running fuzzy_rubby_server standalone:

> I could manage to build and install the LSP by:
> git clone the project
> cd to the project directory
> build the executable  : cargo build --release --target=aarch64-apple-darwin
> symlink  the .../fuzzy_ruby_server/bin/fuzzy_darwin-arm64 binary into the standard bin/. directory
> configure BBEdit to use this binary for the ruby language
> The LSP seems to be working as expected and logged in the LanguageServerProtocol-Ruby.txt file.
> But there is a caveat: BBEdit will freeze when quitting, probably due to the LSP not behaving as expected when asked to shutdown.
> I suspect the LSP does not respond to the [Exit Notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit).
> {"jsonrpc":"2.0","id":2,"method":"shutdown"}Content-Length: 38
> 
> {"jsonrpc":"2.0","result":null,"id":2}Content-Length: 33
> 
> {"jsonrpc":"2.0","method":"exit"} ... 
> If this is indeed the cause, it should be reported to the developer.

With the disclaimer that I've not done anything in rust before, but I didn't see anything in the [server](https://github.com/pheen/fuzzy_ruby_server/blob/master/src/main.rs) to handle "exit" requests. I also couldn't tell for certain if TowerLSP is supposed to handle exit requests without any additional implementation.

**Comment by etherbob** [comment]
Ahh, might indeed be a [TowerLSP](https://github.com/ebkalderon/tower-lsp/issues/399) issue.

**Comment by pheen** [comment]
It should be responding to shutdown requests. As a backup, Fuzzy grabs the editor process and watches it and will automatically shut down when the editor process is no longer available. https://github.com/pheen/fuzzy_ruby_server/blob/master/src/main.rs#L42-L58

**Comment by etherbob** [comment]
@pheen I might be misundersatnding but per https://github.com/ebkalderon/tower-lsp/issues/399 and reports from other users it is not responding to exit requests and the editor itself is hanging waiting for the server to exit.
