### ISSUE TITLE
Can't parse usage of `**`

### ISSUE THREAD

**Issue by a-lavis** [pheen/fuzzy_ruby_server#17]
<img width="843" alt="Screenshot 2023-12-04 at 4 25 42 PM" src="https://github.com/pheen/fuzzy_ruby_server/assets/9829542/2fccb29d-7323-4409-ad9c-76d599f09ab5">

When parsing the below file:
```ruby
# frozen_string_literal: true

def foo(**)
  puts(foo: 1, **) # error `unexpected tRPAREN` at the end of this line
end

foo(bar: 2)
```
The Fuzzy Ruby Server has the error `unexpected tRPAREN`.

When I run this file in Ruby or parse it using [Prism](https://github.com/ruby/prism) it seems to work fine, so I believe the code is valid.

I'm using Ruby 3.2.2 and the only extension in VSCode is the Fuzzy Ruby Server `v1.0.0`.

---

P.S. Thank you for creating an awesome tool!

**Comment by pheen** [comment]
Hey @a-lavis , I'm not sure what Prism is doing but that's not valid Ruby code. `**` in a method definition is for kwargs and requires a variable name after the stars such as `def foo(**a)`.

I'm pretty sure that's still the case in the latest version of Ruby, though please let me know if you can execute the code under MRI Ruby. There isn't actually much I can do here in any case as I didn't build the parser I use https://github.com/lib-ruby-parser/lib-ruby-parser

**Comment by a-lavis** [comment]
Thanks for the quick response @pheen!  As of [Ruby 3.2](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/) it is valid Ruby code:
<img width="610" alt="Screenshot 2023-12-04 at 5 56 11 PM" src="https://github.com/pheen/fuzzy_ruby_server/assets/9829542/b209f6bd-52db-4b39-8021-a0e8ebb2c308">
I can execute the code just by running `ruby test.rb` - not sure if that's different from executing it under MRI Ruby.

Based on [this](https://github.com/lib-ruby-parser/lib-ruby-parser#library-versioning):

>## Library versioning
>
> | Ruby version | lib-ruby-parser version |
> |--------------|-------------------------|
> | 3.0.0        | 3.0.0+                  |
> | 3.1.0        | 4.0.0+ruby-3.1.0        |
>
> Starting from `4.0.0` lib-ruby-parser follows SemVer. Base version increments according to API changes,
> while metadata matches current Ruby version, i.e. `X.Y.Z+ruby-A.B.C` means:
>
> + `X.Y.Z` base version
> + that parses Ruby `A.B.C`
>
> Both versions bump separately.

It sounds like `lib-ruby-parser` doesn't support Ruby 3.2 given that [there are no versions labelled `+ruby-3.2.X`](https://crates.io/crates/lib-ruby-parser/versions).

**Comment by vassyz** [comment]
Can we please re-open this issue? I just upgraded a project to Ruby 3.2.2 and I'm getting errors related to the `**` syntax (Which rubocop auto-corrects by default to). I will disable this extension for now.
