### ISSUE TITLE
[feature-request] Release binary file in Github Releases

### ISSUE THREAD

**Issue by tiev** [pheen/fuzzy_ruby_server#18]
This LSP is so great! The golden feature is that it can also index gems, so I can jump into the gem source.

The only problem for a vim user is the installation. Beside the gem packaging as mentioned in https://github.com/pheen/fuzzy_ruby_server/issues/15 , the executable can also be published through Github Releases using automation.

Furthermore, the package releases can be register with mason.nvim for convenience.

**Comment by technicalpickles** [comment]
Came here to second this.

In the absence of it, having local build/install instructions would be good. Typically, I'd expect `cargo install --path .` to handle it, but I'm seeing some failures (I'll follow up)

As a workaround, I'm installing the extension with vscode, and then checking the directory the fuzzy bin is, ie on macOS:

```
 ls ~/.vscode{-insiders,}/extensions/blinknlights.fuzzy-ruby-server-*/bin/fuzzy 2>/dev/null | head -n 1
```

**Comment by pheen** [comment]
The binaries are available at https://github.com/pheen/fuzzy_ruby_server/tree/master/bin, and build instructions are included as part of https://github.com/pheen/fuzzy_ruby_server#publishing

Sorry I'm not planning to do anymore work on this library in the near future as I no longer develop in Ruby.
