### ISSUE TITLE
Simple trick to enable Gemfile.lock gems indexing with `asdf`

### ISSUE THREAD

**Issue by jmgarnier** [pheen/fuzzy_ruby_server#2]
I use `asdf` so I hacked your super nice Ruby LSP to make it work:
```
brew install rbenv
sudo ln -s  /opt/homebrew/bin/rbenv /usr/local/bin/rbenv
```

Maybe this code https://github.com/pheen/fuzzy_ruby_server/blob/f8618e4bdb8769d1a49c69da4e9bcfead6e932ab/src/persistence.rs#L437-L443 would be easy to tweak. I guess `gem environment home` always work?

**Comment by pheen** [comment]
Thank you for the compliment, super happy you're finding it useful!

Hmm, I can't quite remember why `"eval \"$(/usr/local/bin/rbenv init -)\"` was needed, there doesn't seem to be an obvious reason why it would be required. I will be doing some updates this weekend, I'll take a look. At the very least I'll add a conditional to the command so it checks for `/usr/local/bin/rbenv` before calling it. Hardcoding that path probably also is not ideal 😅
