### ISSUE TITLE
Diagnostics are slower than ruby-lint

### ISSUE THREAD

**Issue by kucho** [pheen/fuzzy_ruby_server#5]
Diagnostics feels slow/laggy compared to ruby-linter. There are times when the syntax already changed, but the highlighted error shows for a couple seconds more. Can we improve it or add a setting to disable this feature altogether?

# Demo Fuzzy Ruby Server
https://github.com/pheen/fuzzy_ruby_server/assets/26698519/9cb3db18-0a9e-4ff5-adbf-6a3aa930bd10

# [Demo ruby-linter](https://marketplace.visualstudio.com/items?itemName=hoovercj.ruby-linter)
https://github.com/pheen/fuzzy_ruby_server/assets/26698519/01b5a234-38a9-4fea-a974-f6e47b3f8091

**Comment by pheen** [comment]
Thanks for the thorough report @kucho . The delay with diagnostics should be totally fixed. I also added a setting to disable diagnostics entirely if you still prefer to use a different extension for that.

I'll close this issue tomorrow when I publish a new version with this and a few other tweaks.

**Comment by pheen** [comment]
Published 0.7.3 to the marketplace that should fix this. Thanks for using the project!
