### ISSUE TITLE
fuzzy panics when using with neovim

### ISSUE THREAD

**Issue by okuuva** [pheen/fuzzy_ruby_server#6]
I tried to set up fuzzy_ruby_server to work with neovim using the instructions in wiki. I got the server registered but it panics when trying to attach to a buffer:
```
[ERROR][2023-10-03 21:17:23] .../vim/lsp/rpc.lua:675	"rpc"	"/Users/oula/bin/fuzzy_ruby_ls"	"stderr"	"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/persistence.rs:301:65
stack backtrace:
   0:        0x1048cdd4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h56d7672c82815b65
   1:        0x1048ec3cc - core::fmt::write::h632b3cc8e66b4f04
   2:        0x1048cb0e4 - std::io::Write::write_fmt::hc28441b249a4971d
   3:        0x1048cdba4 - std::sys_common::backtrace::print::h8057ced4b0f9fdc1
   4:        0x1048cf0cc - std::panicking::default_hook::{{closure}}::h8157fa8f0f7934b5
   5:        0x1048cee5c - std::panicking::default_hook::hdaefe3bfb5fe212c
   6:        0x1048cf5fc - std::panicking::rust_panic_with_hook::h21091a3c79c5da9c
   7:        0x1048cf4cc - std::panicking::begin_panic_handler::{{closure}}::hd2f65b958d3068b8
   8:        0x1048ce12c - std::sys_common::backtrace::__rust_end_short_backtrace::h53ec33e49ec66621
   9:        0x1048cf274 - _rust_begin_unwind
  10:        0x104914be0 - core::panicking::panic_fmt::h3bbf9265d206434c
  11:        0x104914c50 - core::panicking::panic::h23f868a19cef4049
  12:        0x1044a0acc - fuzzy::persistence::Persistence::initialize::h7367f43b7391864f
  13:        0x1044df204 - <fuzzy::Backend as tower_lsp::LanguageServer>::initialize::{{closure}}::hc1c2f7f1269e63aa
  14:        0x1044754c4 - tower_lsp::jsonrpc::router::Router<S,E>::method::{{closure}}::{{closure}}::{{closure}}::h1ea197d786719253
  15:        0x1044ae85c - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h613e9ec883dd1bf2
  16:        0x1045920b4 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h31757aa285ec0320
  17:        0x104523800 - <tower_lsp::service::layers::InitializeService<S> as tower_service::Service<tower_lsp::jsonrpc::Request>>::call::{{closure}}::h21dd8074d30e1cc5
  18:        0x1044c8964 - <tower_lsp::service::LspService<S> as tower_service::Service<tower_lsp::jsonrpc::Request>>::call::{{closure}}::h448f736f6a9545fe
  19:        0x1044b0710 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hae41eed690cb92d4
  20:        0x10458c7a0 - <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::h11d8767901e22ad9
  21:        0x1044c8c18 - <futures_util::stream::stream::buffer_unordered::BufferUnordered<St> as futures_core::stream::Stream>::poll_next::h77cdaab60bad1ddc
  22:        0x104555ae8 - <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next::h6d218202e3fa9c65
  23:        0x104504690 - <futures_util::stream::stream::forward::Forward<St,Si,Item> as core::future::future::Future>::poll::h8be406cadc5b4034
  24:        0x1044b0c14 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hc17a4763188cd072
  25:        0x1045036fc - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h4fe8e8669762510d
  26:        0x104550ff4 - tokio::runtime::park::CachedParkThread::block_on::h634e163b2a224a72
  27:        0x1044bde70 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h09ef955aaed728c9
  28:        0x104590870 - tokio::runtime::runtime::Runtime::block_on::h2ff3fd0abc6ed5d2
  29:        0x1044defbc - fuzzy::main::h1502fb928997c87d
  30:        0x10455d6c0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb9cead3db237584b
  31:        0x10458d17c - std::rt::lang_start::{{closure}}::h3dedce23984350de
  32:        0x1048c5ad4 - std::rt::lang_start_internal::heb9ef1177a8102d0
  33:        0x1044e1ae8 - _main
"
```

/Users/oula/bin/fuzzy_ruby_ls is just a symlink to bin/fuzzy_darwin-arm64. If I try running just `fuzzy_ruby_ls` in my command line it does work.

Cool project, let me know if I can help with debugging this any further.

**Comment by pheen** [comment]
Hey @okuuva , thanks for trying the project! That is cause by a missing default config value. Normally the VSCode extension provides them [here](https://github.com/pheen/fuzzy_ruby_server/blob/master/client/src/extension.ts#L61-L63).

To provide those config values I think you need to update `settings = {}` so it includes them:

```
if not configs.fuzzy_ls then
  configs.fuzzy_ls = {
    default_config = {
      cmd = {'fuzzy'};
      filetypes = {'ruby'};
      root_dir = function(fname)
        return lspconfig.util.find_git_ancestor(fname)
      end;
      settings = {
        allocationType = "ram",
        indexGems = true,
        reportDiagnostics = true
      };
    };
  }
end
```

Let me know if that works, I'll add it to the documentation. I should also update the server so it provides its own default value if one isn't given.

- [ ] Update neovim documentation with config options
- [ ] Add default config values in to the server incase the client doesn't provide them

**Comment by okuuva** [comment]
Tiervâ @pheen, and thanks for a very speedy response!

I figured it was related to those settings but couldn't figure how to pass them to the server. Unfortunately setting those inside the default_config did not help. Neither did passing them via .setup() (`configs.fuzzy_ls.setup({allocationType = "ram"...})`). But looking all the other custom LSP configs I have I realized that they are always wrapped in another table inside settings. I'll try and figure out the right table name for it.

**Comment by pheen** [comment]
Ah it's `init_options` instead of `settings`. [LSP initializationOptions compared to neovim settings](https://neovim.discourse.group/t/initializationoptions-init-options-confusion-and-difference-to-settings/323).

```
if not configs.fuzzy_ls then
  ...
      init_options = {
        allocationType = "ram",
        indexGems = true,
        reportDiagnostics = true
      };
  ...
end
```

That maps directly to `initializationOptions` in the [vscode extension](https://github.com/pheen/fuzzy_ruby_server/blob/master/client/src/extension.ts#L60) so that should work this time.

**Comment by okuuva** [comment]
> Ah it's `init_options` instead of `settings`. [LSP initializationOptions compared to neovim settings](https://neovim.discourse.group/t/initializationoptions-init-options-confusion-and-difference-to-settings/323).
> 
> ```
> init_options = {
>   allocationType = "ram",
>   indexGems = true,
>   reportDiagnostics = true
> };
> ```
> 
> That maps directly to `initializationOptions` in the [vscode extension](https://github.com/pheen/fuzzy_ruby_server/blob/master/client/src/extension.ts?rgh-link-date=2023-10-04T05%3A59%3A32Z#L60) so that should work this time.

Yes, that did the trick! Takkâ ennuv ^^

**Comment by pheen** [comment]
I've added default values for all of the config options so nvim users won't experience a crash if they don't provide config values. I've updated the nvim install instructions to include teh values anyways. Takkâ ennuv @okuuva !
