### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by tachyons** [pheen/fuzzy_ruby_server#8]
I've tried using this in a relatively big project (GitLab). But Memory consumption is very high

<img width="558" alt="Screenshot 2023-11-20 at 3 41 01 PM" src="https://github.com/pheen/fuzzy_ruby_server/assets/3112976/3a67d56e-3864-4ff3-974e-0cb64b91d50d">

**Comment by pheen** [comment]
@tachyons Hello! Very cool project, thanks for giving it a try.

By default the index is kept purely in-memory, but you can change the change the `allocationType` config to `tempdir`. This will mmap the index which should dramatically lower real memory size at the cost of some disk usage.

I found indexing and lookup performance still very good with an mmap index so I'm hoping that can solve the issue for you.

**Comment by inbasagaran007** [comment]
@pheen Is there a way to volumize the mmap directory, as I'm using a dev container-based setup in VScode, each time on opening the VScode in the container the Fuzzy Ruby Server utilizes more memory usage, though I have the mmap config.

Can you please share the path that can be volumized for container setup?

**Comment by pheen** [comment]
Not sure sorry
